### ISSUE TITLE
Assignment slicing incorrect

### ISSUE THREAD

**Issue by jamescheney** [jstolarek/slicer#43] opened 2017-02-23 11:54 UTC
```
let t = trace (
    let a = ref 1 in
    let b = ref 1 in
    let c = ref 1 in
    b := !b + !a - !c;;
    !b) in
bwdSlice (t, 1)
```

In this example the slice retains initial values for a and c but not b, so there may be a bug in the slicing of assignments.

**Comment by jamescheney** [comment] 2017-02-23 12:21
I think the code in the assignment case
```
                  do p <- storeDerefM l
                     (rho2, e2, t2') <- bwdSliceM p t2
                     (rho1, e1, t1') <- bwdSliceM (toValue l) t1
                     storeUpdateHoleM l
```
should be
```
                  do p <- storeDerefM l
                     storeUpdateHoleM l
                     (rho2, e2, t2') <- bwdSliceM p t2
                     (rho1, e1, t1') <- bwdSliceM (toValue l) t1

```

since the first version deletes any demand on l resulting from slicing the subtraces.

**Comment by jstolarek** [comment] 2017-02-23 16:05
Yup, that was the cause. Fixed in `references` branch.

**Closed as completed by jstolarek** 2017-02-23 16:05 UTC
